### PR TITLE
Generalize Riemann theta for N derivatives

### PR DESCRIPTION
**Pull request by jupsal**
A generalization of theorems 3,5,7 of [CRTF] is used to find the radius needed for computing N directional derivatives of the Riemann Theta Function. 

### Goals

- [x] Generalize radius calculation in `radius.pyx`.
- [x] Generalize derivative evaluation in `RiemannTheta`

### CODE REVIEW

**Comment by cswiercz** [comment]
I wrote the functions `radius1` and `radius2` back in so we can use them in testing.

On that note, you should write tests for every function you create. I only realized the value of this after writing a lot of Abelfunctions which is why my request sounds hypocritical. I'll write some simple tests checking the output of `radiusN` against that of `radius1` and `radius2`. If you think there are other tests you can implement then please feel free to do so.

You can obtain the code I just pushed by executing the following in your own repo:

```
$ git remote add upstream https://github.com/abelfunctions/abelfunctions.git
$ git checkout NDerivatives 
$ git pull upstream NDerivatives NDerivatives
```

**Comment by cswiercz** [comment]
I just wanted to bounce some ideas off of you for testing `radiusN`. I'm already working on a test suite for the `radius.pyx` module. The most basic test is to compare the output of `radiusN` with that of `radius1` and `radius2` with identical input. I don't know what data is out there for direct comparison testing. Maybe we can test against some Maple output?

Though, the problem with testing against Maple output is that we're not guaranteed that the Maple code is correct by some other measure. Still, it may be valuable. Not to mention, we already test against Maple output in [`abelfunctions/riemann_theta/tests/test_theta.py`](https://github.com/abelfunctions/abelfunctions/blob/master/abelfunctions/riemann_theta/tests/test_theta.py#L46).

**Comment by jupsal** [comment]
Thanks. I did write some tests comparing the result of `radiusN` with `radius1` and `radius2` for a 2x2 `Omega` and `Omega3` as in [`abelfunctions/riemann_theta/tests/test_theta.py`](https://github.com/abelfunctions/abelfunctions/blob/master/abelfunctions/riemann_theta/tests/test_theta.py#L46) but did not know how best to include them here so I avoided it pushing it. 

I think testing against Maple and also taking numerical derivatives are good. I have a proof that the formula used for computing the radius is correct so it seems as if they match up for `N=1` and `N=2`, we can assume that the higher derivatives are behaving accordingly (assuming the proofs in those cases is correct as well).

**Comment by cswiercz** [comment]
> Thanks. I did write some tests comparing the result of `radiusN` with `radius1` and `radius2` for a 2x2 `Omega` and `Omega3` as in [`abelfunctions/riemann_theta/tests/test_theta.py`](https://github.com/abelfunctions/abelfunctions/blob/master/abelfunctions/riemann_theta/tests/test_theta.py#L46) but did not know how best to include them here so I avoided it pushing it. 

Awesome. I decided to write up a separate testing module `test_radius.py` since, after all, all of the radius computing code is in a separate module. You can add to it once I push my changes.

> I think testing against Maple and also taking numerical derivatives are good. I have a proof that the formula used for computing the radius is correct so it seems as if they match up for `N=1` and `N=2`, we can assume that the higher derivatives are behaving accordingly (assuming the proofs in those cases is correct as well). 

I agree. We'll need to modify the Riemann theta code itself in order to compute the new derivatives. I think `finite_sum.c` only performs the arithmetic for the first and second derivatives.

Now is the time to ask ourselves if we want to keep the C code or rewrite some things in Sage. Initial thoughts? I have many.

**Comment by cswiercz** [comment]
Notes from meeting about evaluating theta for multiple derivatives:

* **Save work by computing permutations:** `O(n!)` work for an order `n` derivative to compute all possible permutations of `O(g^n)` indices. However, a single theta function evaluation is about `O(g^g)` work, which is terrible. Therefore, it is in our best interest to spend the time computing permutations and only evaluating on a smaller simplex and copying than to evaluate at every possible derivative.
* **Muli-looping** We need to do something of the form,

  ```python
  for n1 in range(g): 
    for n2 in range(n1):
      ...
                for nk in range(nk-1):
                  val[n1,n2,...,nk] = out
  ```

  to compute the `k`-tensor representing the `k`th derivative of theta.

**Comment by cswiercz** [comment]
> Thanks. I did write some tests comparing the result of `radiusN` with `radius1` and `radius2` for a 2x2 `Omega` and `Omega3` as in [`abelfunctions/riemann_theta/tests/test_theta.py`](https://github.com/abelfunctions/abelfunctions/blob/master/abelfunctions/riemann_theta/tests/test_theta.py#L46) but did not know how best to include them here so I avoided pushing them.

By the way, the way that you would do this is to create a commit with your changes in your local`NDerivatives` branch, pull from my `NDerivatives` branch at

```
https://github.com/abelfunctions/abelfunctions.git
```

into your local`NDerivatives` branch, and then push up to your remote `NDerivatives` branch. (So I can see what you've done.

However, I think `test_radius.py` would be a better location for these tests. You should move them there.

**Comment by cswiercz** [comment]
Actually, could you update your version of `NDerivatives` with all of my changes? Just curious about the automated tests. *"All checks have passed"*, I think, refers to your branch.

**Comment by cswiercz** [comment]
@jupsal I wrote up the following last night / this morning for computing the z-directional derivatives in the "lower simplex" of the derivative tensor grid. That is, it computes the minimal set of z-directional derivatives such that all remaining derivatives are just permutations of this index set.

I'm sure there's a name for this. I'm actually going to a dinner party tonight with a friend who's a combinatorialist. I'm sure he has seen this before.

Anyway, here is the code:

```python
def lower_simplex(g, N):
    return _lower_simplex(g, N, [], [])

def _lower_simplex(num_elements, current_degree, results, current_indices):
    # if the current degree is zero then we have reached the end of an index
    # list. That is, current_indices is of full length
    #
    #     [i1, i2, ..., iN]
    #
    # where N == current_degree. append to results array and exit.
    if current_degree == 0:
        results.append(current_indices)
        return

    # otherwise, we are still not at the end of this tree branch. generate the
    # next set of lower simplex indices.
    for i in range(num_elements):
        _lower_simplex(i+1, current_degree-1, results, current_indices+[i])

    # every index set has been computed. return all results.
    return results
```
I'm trying to come up with a [generator](https://jeffknupp.com/blog/2013/04/07/improve-your-python-yield-and-generators-explained/) version to save on memory since the number of vectors we need to compute take up `O(g^N)` space where `g` is the genus and `N` is the order of the derivative.

**Comment by cswiercz** [comment]
I call this good. I'm going to create an enhancement issue for the N-order gradient indexing. It might be useful in the future, especially given the issue we discussed privately about how, when taking the directional derivative with direction `U` the accuracy seems to be low if `||U||` is large.

**Comment by jupsal** [comment]
Oh no, I didn't commit my tests yet because I was going to add numerical
derivatives but have not come up with a good way to do it yet.

**Comment by cswiercz** [comment]
No worries. Just commit to `jupsal:NDerivatives` again.

**Pull request merged**
