### PR TITLE
say what to do with wrong zip archive naming

### PR DESCRIPTION
**Pull request by dimpase**
see the discussion https://groups.google.com/d/msg/sage-support/GW1PpAY9P_A/wSPThj7_CQAJ

### CODE REVIEW

**Comment by dimpase** [comment]
this is meant to fix
https://github.com/abelfunctions/abelfunctions/issues/119

**Comment by videlec** [comment]
It would be better to provide directly the spkg (even better with version number) and not let the user do it!

**Comment by cswiercz** [comment]
@dimpase 's solution is good for now. I agree with @videlec , though, that there should be a better download option. I guess I hadn't anticipated this much interest in my work!

**Comment by dimpase** [comment]
even better it would be nice to have it as an "official" experimental package in Sage....

**Comment by cswiercz** [comment]
Now that I know people in the Sage community are interested I should! Is there a way for Sage to obtain the most recent version or do I have to specify a version number and keep a hand-rolled tarball around for each version? I ask because Abelfunctions is still a (relatively) fast-changing project...

...at least until I finish my Ph.D.

**Comment by dimpase** [comment]
have a look at how a typical spkg configuration is made in build/pkgs/
Indeed, a new release needs to be manually hooked up in build/pkgs/ via a tarfile you provide upstream.
(upon a release the upstream tarball gets copied to mirrors, so then if you want to do an update you will need to do a new release, etc)

**Comment by lesshaste** [comment]
It is worth noting http://trac.sagemath.org/ticket/6371 which claims an implementation of the Riemann Theta function should be in sage 7.1.  I suspect this isn't correct looking at the changelog but nonetheless it would be interesting to compare http://git.sagemath.org/sage.git/commit/?id=403854b74553ba7856b0f1cf7029b52450e8152c .

**Comment by dimpase** [comment]
On Tue, Mar 29, 2016 at 3:34 PM, lesshaste <notifications@github.com> wrote:

> It is worth noting http://trac.sagemath.org/ticket/6371 which claims an
> implementation of the Riemann Theta function should be in sage 7.1.
>
no, it is not closed, its status is 'needs work'. Someone should bump up
the milestone to at least 7.2, as it is not automatic.

**Comment by lesshaste** [comment]
Thanks. I notice it is owned by @cswiercz  .

**Pull request merged**
