### PR TITLE
[WIP] Replace TravisCI with GitHub Actions

### PR DESCRIPTION
**Pull request by rparini**
- Resolves https://github.com/abelfunctions/abelfunctions/issues/194
- Removes TravisCI config and replaces with GitHub Actions
- Pins test dependencies with new `test-requirements.txt` file

### CODE REVIEW

**Comment by rparini** [comment]
@cswiercz thought you might like to review but no worries if you don't have time, I'll merge in a week if no comments.

**Review by cswiercz — APPROVED** [review]
Looks good. Thanks for leading this!

Amazing that Sage still uses Python 2.x...

**Comment by slel** [comment]
Not quite: Sage >= 9.2 no longer supports Python 2.

The transition took some time, and some steps:

- Sage 8.x was primarily Python 2 based,
  with increasing support for Python 3
- Sage 9.0 and 9.1 were primarily Python 3 based,
  while still offering the option to use Python 2.7
- Sage 9.2 and 9.3 and the current 9.4 cycle
  have all been Python 3 only.

As set up here, the continuous integration targets
the current version of Sag but also a few past versions,
including some that were still primarily based on Python 2.7.

**Comment by cswiercz** [comment]
@slel Good to know! I was always impressed with Sage's self-contained build environment.

**Comment by rparini** [comment]
Yeah, I couldn't find a stated "end of life" or support policy for SageMath versions but I imagine we'll want to drop support and testing against these old versions at some point.

**Pull request merged**
